name: Makefile CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3


    - name: Install tkinter
      run: sudo apt-get update && sudo apt-get install -y python3-tk

    - name: Install dependancies
      run: pip install -r requirements.txt && pip install -e . && pip install pydantic

    - name: Run tests
      run: make test

