name: Makefile CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Install dependancies
      run: pip install -r requirements.txt && pip install -e .

    - name: Run tests
      run: make test
      
